const mongoose = require("mongoose");

const documentSchema = new mongoose.Schema(
  {
    caseId: {
      type: String,
      required: true,
      index: true,
    },
    filename: {
      type: String,
      required: true,
    },
    fileUrl: {
      type: String, // Local path or cloud URL
      required: true,
    },
    type: {
      type: String,
      enum: [
        "Charge Sheet",
        "Forensic",
        "Medical",
        "Statement",
        "Court Order",
        "Final Judgment",
        "Judicial Notice",
        "Bail Order",
        "Witness Summons",
        "Miscellaneous",
        "Supporting Document"
      ],
      required: true,
    },
    uploadedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    // Used for judicial signatures and cryptographic verification
    digitalSignature: {
      method: { type: String, enum: ["canvas", "digilocker", "upload", "none"], default: "none" },
      officerName: { type: String, default: null },
      timestamp: { type: Date, default: null },
      documentHash: { type: String, default: null }, // SHA-256 Hash of uploaded file
      cryptographicSeal: { type: String, default: null }, // HMAC seal generated by server
      verified: { type: Boolean, default: false }
    },
    // Blockchain fields (same as Evidence model)
    blockchainStatus: {
      type: String,
      enum: ["NOT_ANCHORED", "ANCHORED", "FAILED"],
      default: "NOT_ANCHORED",
    },
    blockchainTxHash: { type: String, default: null },
    blockchainAnchoredHash: { type: String, default: null },
    blockchainAnchoredAt: { type: Date, default: null },
    size: {
      type: Number, // File size in bytes
      default: 0
    }
  },
  {
    timestamps: true,
  }
);

module.exports = mongoose.model("Document", documentSchema);
